name: messagebird
version: 1.3.4
description: This repository provides a Dart client for MessageBird's REST API.
homepage: https://github.com/messagebird/dart-rest-api
repository: https://github.com/messagebird/dart-rest-api.git
documentation: https://developers.messagebird.com/api/
dependencies:
  http: ^0.11.0
  yaml: ^2.0.0
dev_dependencies:
  test: ^1.6.0
environment:
  sdk: '>=2.5.0 <3.0.0'
